import { PlanetData } from './types';

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'terrestrial',
    description: 'The smallest planet in our solar system and closest to the Sun. It has a cratered, dark grey surface.',
    color: '#A5A5A5',
    radius: 0.8,
    distance: 14,
    speed: 1.5,
    rotationSpeed: 0.004,
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'terrestrial',
    description: 'Spinning in the opposite direction to most planets, Venus is the hottest planet with a thick atmosphere.',
    color: '#E3BB76',
    radius: 1.4,
    distance: 22,
    speed: 1.1,
    rotationSpeed: 0.002,
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'terrestrial',
    description: 'Our home planet, the only place we know of so far that’s inhabited by living things.',
    color: '#2233FF',
    radius: 1.5,
    distance: 32,
    speed: 1.0,
    rotationSpeed: 0.01,
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'terrestrial',
    description: 'A dusty, cold, desert world with a very thin atmosphere. The Red Planet.',
    color: '#E27B58',
    radius: 1.1,
    distance: 42,
    speed: 0.8,
    rotationSpeed: 0.009,
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'gas_giant',
    description: 'More than twice as massive as all the other planets combined. A gas giant with iconic bands.',
    color: '#C88B3A',
    radius: 4.0,
    distance: 65,
    speed: 0.4,
    rotationSpeed: 0.04,
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'gas_giant',
    description: 'Adorned with a dazzling, complex system of icy rings.',
    color: '#E4DBB2',
    ringColor: '#C0B090',
    radius: 3.5,
    distance: 90,
    speed: 0.3,
    rotationSpeed: 0.038,
    hasRings: true,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'ice_giant',
    description: 'It rotates at a nearly 90-degree angle from the plane of its orbit.',
    color: '#93B8BE',
    radius: 2.2,
    distance: 115,
    speed: 0.2,
    rotationSpeed: 0.03,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'ice_giant',
    description: 'The first planet located through mathematical calculations rather than by telescope.',
    color: '#4B70DD',
    radius: 2.1,
    distance: 135,
    speed: 0.1,
    rotationSpeed: 0.032,
  },
];

export const SUN_DATA = {
  radius: 7,
  color: '#FFD700',
  emissiveIntensity: 5, 
};